services:
  shell:
    build: .
    entrypoint:
      - /bin/sh
    image: 368099029718.dkr.ecr.us-west-2.amazonaws.com/seismic-api
    init: true
    volumes:
      - ./:/home/python/seismic-api
    working_dir: /home/python/seismic-api
