services:
  shell:
    build: .
    entrypoint:
      - /bin/sh
    image: ghcr.io/informatica-na-presales-ops/seismic-api
    init: true
    volumes:
      - ./:/home/python/seismic-api
    working_dir: /home/python/seismic-api
